### ISSUE TITLE
Add and validate modifiers for fields/ methods

### ISSUE THREAD

**Issue by kiyomih** [jyoo980/TypeScript.ts#43]
We currently don't add modifiers for fields and methods and allow for random input e.g.:

`function randomword nameofMethod` will generate a file, throw no errors

**Comment by jyoo980** [comment]
Ongoing in #46 

Access modifier generation is working - I'm leaning toward throwing errors for invalid modifiers as a nice to have. No sane developer is going to write 

`function ayylmao nameOfMethod`

I feel

**Comment by jyoo980** [comment]
Work merged!
